task: 'uncond'

# Dataset configuration
num_class: 4
train_batch_size: 32
test_batch_size: 128
width: 513
height: 750
dataset_cls: 'pku'

# Paths
paths:
  base: "/mnt/data/ly24/dataset/pku/split"
  train:
    inp_dir: "train/inpaint"
    sal_dir: "train/saliency"
    sal_sub_dir: "train/saliency_sub"
    annotated_dir: "csv/train.csv"
    salbox_dir: "csv/train_sal.csv"
  test:
    inp_dir: "val/inpaint"
    sal_dir: "val/saliency"
    sal_sub_dir: "val/saliency_sub"
    annotated_dir: "csv/val.csv"
    salbox_dir: "csv/val_sal.csv"

# Model parameters
max_elem: 16
lr: 1.0e-4
epochs: 500
gradient_clipping: 1.0
d_model: 512
n_head: 8
n_layers: 4
feature_dim: 1024

# Runtime configuration
num_workers: 16
log_test_epochs: 5
base_check_dir: '/mnt/data/ly24/checkpoint/pku'
imgname_order_dir: '/home/ly24/code/ditl/output/ptfile/image_name_order'

# Dynamic configuration
datetime: null